name: c3k
dependencies:
  - python=3.8
  # infrastructure
  - ipython
  # scientific computing
  - numpy
  - scipy
  - matplotlib
  - h5py
  # astro
  - astropy

# --- via setup.py ---
# prospector, sedpy, ckc, python-fsps